stages:
  - install-lint
  - build-test
  - deploy
app-install-lint:
  image: node:10.16
  stage: install-lint
  before_script:
    - yarn
  script:
    - yarn lint
  artifacts:
    paths:
      - node_modules/
app-build-test:
  image: node:10.16
  stage: build-test
  only:
    - master
  script:
    - yarn build
    - yarn -v && node -v # @todo code test commands
app-deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Done!" # @todo code deploy commands
  dependencies: []
