stages:
  - install-lint
  - deploy
app-install-lint:
  stage: install-lint
  image: node:12.13
  before_script:
    - yarn
  script:
    - yarn lint
  artifacts:
    paths:
      - node_modules/
app-deploy:
  stage: deploy
  image: node:12.13
  only:
    - master
  before_script:
    - yarn package
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>./dist/.npmrc
    - npm publish dist
  after_script:
    - echo "The package is deployed to NPM registery!"
  dependencies: []
