stages:
  - install-lint
  - build-test
  - deploy
cache:
  paths:
    - node_modules/
    - dist/
app-install-lint:
  image: node:10.14
  stage: install-lint
  before_script:
    - yarn
  script:
    - yarn lint
app-build-test:
  image: node:10.14
  stage: build-test
  only:
    - master
  script:
    - yarn build
    - yarn -v && node -v # @todo code test commands
app-deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Done!" # @todo code deploy commands
