image: node:10.14

stages:
  - install-lint
  - build-test
  - deploy
cache:
  paths:
    - node_modules/
    - dist/
app-install-lint:
  stage: install-lint
  script:
    - npm install --progress=false && npm update --progress=false
    - npm run lint
app-build-test:
  stage: build-test
  only:
    - master
  script:
    - npm run build
    - npm -v # @todo code test commands
app-deploy:
  stage: deploy
  only:
    - master
  script:
    - node -v # @todo code deploy commands
