image: node:latest

stages:
  - install
  - lint
  - build
  - test
  - deploy
cache:
  paths:
    - node_modules/
    - dist/
app_install:
  stage: install
  script:
    - npm install
    - npm update
  artifacts:
    paths:
      - node_modules/
app_lint:
  stage: lint
  script:
    - npm run lint
app_build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
app_test:
  stage: test
  script:
    - npm -v
app_deploy:
  stage: deploy
  script:
    - node -v
