name: "Install"
on:
  workflow_run:
    workflows: [ "Production" ]
    types: [ 'completed' ]
jobs:
  install:
    strategy:
      matrix:
        # Test against different operating systems
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        # Test against different Node.js versions
        node: [ 14, 16, 18, 20, 'current' ]

    # The runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: "Initialize package configuration"
        run: npm init -y

      - name: "Install CacheServer package"
        run: npm i @sapkotamadan/cache-server

      - name: "Display installed packages"
        run: npm list --depth=0
