# This workflow is triggered when the Production workflow is completed.
name: "Install"

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [ "Production" ]
    types: [ 'completed' ]

jobs:
  install:
    strategy:
      matrix:
        # Test against different operating systems
        os: [ ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-latest, windows-latest ]
        # Test against different Node.js versions
        node: [ 14, 16, 18, 20, 'current' ]

    # The runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: "Initialize package configuration"
        run: npm init -y

      - name: "Install CacheServer package"
        run: npm i @sapkotamadan/cache-server

      - name: "Display installed packages"
        run: npm list --depth=0
